global:
  scrape_interval:     15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "node-host"
    static_configs:
    - targets: ["node-exp-host:9100"]

  - job_name: "cadvisor"
    scrape_interval: 10s 
#    metrics_path: "/containers"
    static_configs:
      - targets: ["cadvisor:8080"]
#        labels:
#          group: "cadvisor"
